### ISSUE TITLE
Please add the `racket` topic 

### ISSUE THREAD

**Issue by spdegabrielle** [LeifAndersen/racket-sml#1]
Hi Leif,

Please add the `racket` topic - I think others will be interested and this will help them find it at
https://github.com/topics/racket

https://help.github.com/en/articles/classifying-your-repository-with-topics

Kind regards, 

Stephen

**Comment by LeifAndersen** [comment]
TIL topics exist. Sorry about taking so long to notice this. I've done it now though. :)
